ka/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, HiddenField, TextAreaField, ValidationError
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    name = StringField('Title', validators=[DataRequired()])
    text = TextAreaField('Content', validators=[DataRequired()])

    def validate_name(self, field):
        if '_' in field.data:
            raise ValidationError('Underscores are not allowed in titles.')
        if field.data.startswith('&'):
            raise ValidationError("The first character of a title cannot be a '&'")

    def validate_text(self, field):
        if '<script' in field.data:
            raise ValidationError('Please see https://youtu.be/dQw4w9WgXcQ!')


class DeletePostForm(FlaskForm):
    delete = HiddenField('Delete')

ka/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from ka.database import get_page
from ka import db
from ka.models import Post, Visibility, User, Tag, Feature
from ka.posts.forms import PostForm, DeletePostForm
from sqlalchemy import or_, nullslast


posts_app = Blueprint('posts', __name__)


@posts_app.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(name=form.name.data, text=form.text.data, composer=current_user)
        post.tags = Tag.extract_tags(post.text)
        post.composer.count_posts = post.composer.count_posts + 1
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('posts.posts'))
    return render_template('create_post.html', title='New Post',
                           form=form, legend='New Post')


@posts_app.route("/post/<string:post_path>")
@login_required
def post(post_path):
    p = Post.query.filter_by(path=post_path).first()
    if not p:
        abort(404)
    if p.visibility == Visibility.HIDDEN:
        abort(404)
    return render_template('post.html', title=p.name, post=p)


@posts_app.route("/post/<string:post_path>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_path):
    p = Post.query.filter_by(path=post_path).first()
    if not p:
        abort(404)
    if p.composer != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        p.name = form.name.data
        p.text = form.text.data
        p.tags = Tag.extract_tags(p.text)
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_path=p.path))
    elif request.method == 'GET':
        form.name.data = p.name
        form.text.data = p.text
    return render_template('create_post.html', title='Edit Post',
                           form=form, legend='Edit Post')


@posts_app.route("/post/<string:post_path>/delete", methods=['GET','POST'])
@login_required
def delete_post(post_path):
    p = Post.query.filter_by(path=post_path).first()
    if not p:
        abort(404)
    if p.user_id != current_user.id:
        abort(403)

    form = DeletePostForm()
    if form.validate_on_submit():
        p.composer.count_posts = p.composer.count_posts - 1
        db.session.delete(p)
        db.session.commit()
        flash('Your post has been deleted!', 'success')
        return redirect(url_for('posts.posts'))

    return render_template('delete_post.html', title='Delete Post', form=form, post=p)


@posts_app.route('/posts', methods=['GET'])
@login_required
def posts():
    page = request.args.get('page', 1, type=int)
    page_result = get_page(
        Post.query
            .join(Feature, (Post.id == Feature.content_id), isouter=True)
            .filter(Post.visibility == Visibility.PUBLIC)
            .order_by(
                nullslast(Feature.pinned.desc()),
                nullslast(Feature.created.desc()),
                Post.created.desc(),
            ),
        page
    )
    return render_template('posts.html', title='Posts', result=page_result)


@posts_app.route("/user/<string:user_path>/posts")
@login_required
def user_posts(user_path):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(path=user_path).first()
    if not user:
        abort(404)
    page_result = get_page(
        Post.query
            .filter(Post.user_id == user.id)
            .filter(or_(Post.visibility == Visibility.PUBLIC, Post.visibility == Visibility.PRIVATE))
            .order_by(Post.count_favorites.desc(), Post.created.desc()),
        page
    )
    return render_template(
        'user_posts.html',
        title='Posts by ' + user.name,
        filtered_on=user,
        result=page_result
    )



# *************************************************
#  Template Tests
# *************************************************


@posts_app.app_template_test("User")
def is_user(o):
    return isinstance(o, User)

ka/scores/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from ka.database import get_page
from ka import db
from ka.models import Score, Measure, to_ordinal_string, ForPlayers, Visibility, User, Tag, Feature, tempo_alt_text, dynamic_alt_text
from ka.scores.forms import ScoreForm, MeasureForm, DeleteMeasureForm, DeleteScoreForm
from datetime import datetime
from sqlalchemy import or_, and_, case, nullslast, func, desc, text


scores_app = Blueprint('scores', __name__)


@scores_app.route("/score/new", methods=['GET', 'POST'])
@login_required
def new_score():
    form = ScoreForm()
    if form.validate_on_submit():
        score = Score(
            name=form.name.data,
            composer=current_user,
            text=form.text.data,
            measures=[],
            count_plays=0,
            count_favorites=0,
            for_players=ForPlayers[form.for_players.data],
            created=datetime.utcnow()
        )
        score.tags = Tag.extract_tags(score.text)
        score.composer.count_scores = score.composer.count_scores + 1
        db.session.add(score)
        db.session.commit()
        flash('Your score has been created!', 'success')
        return redirect(url_for('scores.new_measure', score_path=score.path))
    form = ScoreForm(for_players='TwoAny')  # otherwise will default to 'one man'
    return render_template('create_score.html', title='New Score',
                           form=form, legend='New Score')


@scores_app.route("/score/<string:score_path>/measure/new", methods=['GET', 'POST'])
@login_required
def new_measure(score_path):
    s = Score.query.filter_by(path=score_path).first()
    if not s:
        abort(404)
    if s.composer != current_user:
        abort(403)
    form = MeasureForm()
    if form.validate_on_submit():
        m = Measure(
            _name=form.name.data,
            tempo=form.tempo.data,
            dynamic=form.dynamic.data,
            text=form.text.data,
            duration=form.duration.data,
            created=datetime.utcnow(),
            _ordinal=max((x.ordinal for x in s.measures)) + 1 if s.measures else 0,
            score=s
        )
        db.session.add(m)
        db.session.add(s)
        db.session.commit()
        flash('Your measure has been created!', 'success')
        return redirect(url_for('scores.new_measure', score_path=s.path))
    else:
        ordinal = max((x.ordinal for x in s.measures)) + 1 if s.measures else 0
        name = to_ordinal_string(ordinal) + ' Measure'
        form.name.data = name
        if s.measures:
            prev_measure = s.measures[-1]
            form.duration.data = prev_measure.duration
            form.tempo.data = prev_measure.tempo.value
            form.dynamic.data = prev_measure.dynamic.value
    return render_template('create_measure.html',
                           title='New Measure',
                           form=form,
                           legend='New Measure',
                           score=s,
                           measures=s.measures,
                           append=True)


@scores_app.route("/score/<string:score_path>/measure/<string:measure_path>/new-measure-before", methods=['GET', 'POST'])
@login_required
def new_measure_before(score_path, measure_path):
    s = Score.query.filter_by(path=score_path).first()
    if not s:
        abort(404)
    if s.composer != current_user:
        abort(403)

    above_this_measure = Measure.query.filter_by(path=measure_path).first()
    if not above_this_measure:
        abort(404)
    if above_this_measure.score.id != s.id:
        abort(404)

    index = above_this_measure.ordinal

    measure = Measure()
    form = MeasureForm()
    if form.validate_on_submit():
        measure = Measure(
            _name=form.name.data,
            tempo=form.tempo.data,
            dynamic=form.dynamic.data,
            text=form.text.data,
            duration=form.duration.data,
            created=datetime.utcnow()
        )

        s.measures = s.measures[:index] + [measure] + s.measures[index:]
        for i, m in enumerate(s.measures):
            m.ordinal = i
        db.session.add(s)
        db.session.commit()
        flash('Your measure has been created!', 'success')
        return redirect(url_for('scores.score', score_path=s.path))
    else:
        measure.id = -1
        measures = list(s.measures)[:index] + [measure] + list(s.measures)[index:]

    return render_template('create_measure.html',
                           title='New Measure',
                           form=form,
                           legend='New Measure',
                           score=s,
                           measures=measures,
                           current_measure=measure,
                           append=False)


@scores_app.route("/score/<string:score_path>/measure/<string:measure_path>/new-measure-after", methods=['GET', 'POST'])
@login_required
def new_measure_after(score_path, measure_path):
    s = Score.query.filter_by(path=score_path).first()
    if not s:
        abort(404)
    if s.composer != current_user:
        abort(403)

    below_this_measure = Measure.query.filter_by(path=measure_path).first()
    if not below_this_measure:
        abort(404)
    if below_this_measure.score.id != s.id:
        abort(404)

    index = below_this_measure.ordinal + 1

    measure = Measure()
    form = MeasureForm()
    if form.validate_on_submit():
        measure = Measure(
            _name=form.name.data,
            tempo=form.tempo.data,
            dynamic=form.dynamic.data,
            text=form.text.data,
            duration=form.duration.data,
            created=datetime.utcnow()
        )
        s.measures = s.measures[:index] + [measure] + s.measures[index:]
        for i, m in enumerate(s.measures):
            m.ordinal = i
        db.session.add(s)
        db.session.commit()
        flash('Your measure has been created!', 'success')
        return redirect(url_for('scores.score', score_path=s.path))
    else:
        measure.id = -1
        measures = list(s.measures)[:index] + [measure] + list(s.measures)[index:]

    return render_template('create_measure.html',
                           title='New Measure',
                           form=form,
                           legend='New Measure',
                           score=s,
                           measures=measures,
                           current_measure=measure,
                           append=False)


@scores_app.route("/score/<string:score_path>")
@login_required
def score(score_path):
    s = Score.query.filter_by(path=score_path).first()
    if not s:
        abort(404)
    if s.visibility == Visibility.HIDDEN:
        abort(404)
    variation = None
    if s.variation_on_id:
        variation = Score.query.get(s.variation_on_id)
    title = s.name + ' by ' + s.composer.name
    return render_template('score.html', title=title, score=s, variation=variation, measures=s.measures)


@scores_app.route("/score/<string:score_path>/variations")
@login_required
def score_variations(score_path):
    s = Score.query.filter_by(path=score_path).first()
    if not s:
        abort(404)
    if s.visibility == Visibility.HIDDEN:
        abort(404)
    page = request.args.get('page', 1, type=int)
    page_result = get_page(
        Score.query
            .filter(Score.visibility == Visibility.PUBLIC)
            .filter(Score.variation_on_id == s.id)
            .order_by(desc(text("count_plays + count_favorites")), Score.created.desc()),
        page
    )
    title = 'Variations on ' + s.name + ' by ' + s.composer.name
    return render_template(
        'scores.html',
        title=title,
        filtered_on=s,
        result=page_result
    )


@scores_app.route("/score/<string:score_path>/measure/<string:measure_path>")
@login_required
def measure(score_path, measure_path):
    s = Score.query.filter_by(path=score_path).first()
    if not s:
        abort(404)
    matches = list(filter(lambda x: x.path == measure_path, s.measures))
    if not matches:
        abort(404)
    m = matches[0]

    if s.visibility == Visibility.HIDDEN:
        abort(404)

    prev_ord = m.ordinal - 1
    matches = list(filter(lambda x: x.ordinal == prev_ord, s.measures))
    prev_measure = None
    if matches:
        prev_measure = matches[0]

    next_ord = m.ordinal + 1
    matches = list(filter(lambda x: x.ordinal == next_ord, s.measures))
    next_measure = None
    if matches:
        next_measure = matches[0]

    title = m.name + ' from ' + m.score.name
    return render_template(
        'measure.html',
        title=title,
        score=s,
        measure=m,
        prev_measure=prev_measure,
        next_measure=next_measure,
        show_controls=True
    )


@scores_app.route("/score/<string:score_path>/update", methods=['GET', 'POST'])
@login_required
def update_score(score_path):
    s = Score.query.filter_by(path=score_path).first()
    if not s:
        abort(404)
    if s.composer != current_user:
        abort(403)
    form = ScoreForm()
    if form.validate_on_submit():
        s.name = form.name.data
        s.text = form.text.data
        s.for_players = form.for_players.data
        s.tags = Tag.extract_tags(s.text)
        db.session.commit()
        flash('Your score has been updated!', 'success')
        if s.measures:
            return redirect(url_for('scores.update_measure', score_path=s.path, measure_path=s.measures[0].path))
        else:
            return redirect(url_for('scores.new_measure', score_path=s.path))
    elif request.method == 'GET':
        form.name.data = s.name
        form.text.data = s.text
        form.for_players.data = s.for_players.name
    return render_template('create_score.html', title='Edit Score',
                           form=form, legend='Edit Score')

ka/search/routes.py
from flask import (current_app, render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from ka.elasticsearch import INDEX_PREFIX
from ka.models import Score, Post, User, Measure, to_ordinal_string


search_app = Blueprint('search', __name__)


@search_app.route("/search", methods=['GET', 'POST'])
@login_required
def search():
    query = request.args.get('query').strip() if request.args.get('query') else ''
    scores, count = [], 0

    if query:
        scores, count = Score.search(query, 1, 20)
        unique_scores = { score.id: score for score in scores }  # TODO: unable to collapse on _id
        scores = unique_scores.values()

        index = INDEX_PREFIX + '*'
        # results = current_app.elasticsearch.search(
        #     index=index,
        #     body={
        #         'query': {
        #             'query_string': {
        #                 'query': query
        #             }
        #         },
        #     }
        # )
    #ids = [int(hit['_id']) for hit in search['hits']['hits']]
    #count = search['hits']['total']['value']
    #print(f'elasticsearch -> search doc with query {query} from {index}')
    #print(f"ids: {ids}, count {count}")

    return render_template(
        'search.html',
        title='Search',
        query=query,
        scores=scores
    )

ka/theme/routes.py
from flask import Blueprint, request, render_template, abort
from flask_login import login_required
from sqlalchemy.orm import with_polymorphic
from sqlalchemy import func
from ka.models import KaBase, Tag, tag_association, User, Score, Post
from ka.database import get_page, PageResult
from ka import db

theme_app = Blueprint('theme', __name__)


@theme_app.route('/themes', methods=['GET'])
@login_required
def themes():
    results = Tag.tag_counts()
    return render_template(
        'themes.html',
        title='Themes',
        results=results
    )


@theme_app.route('/theme/<string:name>', methods=['GET'])
@login_required
def theme(name):
    page = request.args.get('page', 1, type=int)
    t = Tag.query.filter(Tag.name == name).first()
    if not t:
        abort(404)
    content = with_polymorphic(KaBase, [User, Score, Post], flat=True)
    page_result = get_page(
        db.session.query(content)\
        .select_from(Tag)\
        .join(tag_association)\
        .join(content)\
        .filter(tag_association.c.tag_id == t.id)
        .order_by(content.created.desc()),
        page
    )
    return render_template(
        'theme.html',
        title=t.name + ' themed',
        name=name,
        result=page_result
    )

ka/templates/create_post.html
{% extends "base.html" %}

{% from 'macros.html' import view_submit_button %}
{% from 'macros.html' import view_formatting_help %}

{% block content %}
<div class="container-md">
<div class="card">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="title text-center"><span>{{ legend }}</span></legend>
            <div class="form-group">
                {{ form.name.label(class="form-control-label") }}
                {% if form.name.errors %}
                    {{ form.name(class="form-control form-control-lg is-invalid content", autofocus=True) }}
                    <div class="invalid-feedback">
                        {% for error in form.name.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.name(class="form-control form-control-lg content", autofocus=True) }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.text.label(class="form-control-label") }}
                {% if form.text.errors %}
                    {{ form.text(class="form-control form-control-lg is-invalid", rows="20") }}
                    <div class="invalid-feedback">
                        {% for error in form.text.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {{ view_formatting_help('text-left') }}
                {% else %}
                    {{ form.text(class="form-control form-control-lg", rows="20") }}
                    {{ view_formatting_help('text-left') }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group float-right">
            <div class="page-controls">
                    {{ view_submit_button('fa-save') }}
            </div>
        </div>
    </form>
</div>
</div>
{% endblock content %}

ka/templates/delete_measure.html
{% extends "base.html" %}

{% from 'macros.html' import view_submit_button %}
{% from 'macros.html' import view_score_title %}
{% from 'macros.html' import view_control %}

{% block content %}
<div class="container-md">
<div class="card">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <div>Are you sure you want to delete</div>
        <div>
            <a href="{{ url_for('scores.measure', score_path=measure.score.path, measure_path=measure.path) }}" class="measure-title">{{ measure.name }}</a>
        </div>
        <div>from the score {{ view_score_title(score.name, score.path) }}?</div>
        <fieldset class="form-group">
            <div class="form-group">
                {{ form.delete(class="form-control form-control-lg") }}
            </div>
        </fieldset>
        <div class="form-group">
            <div class="page-controls">
                    {{ view_control(url_for('scores.score', score_path=score.path), 'fa-undo') }}
                    {{ view_submit_button('fa-times') }}
            </div>
        </div>
    </form>
</div>
</div>
{% endblock content %}

ka/templates/ending.html
{% extends "base.html" %}

{% from 'macros.html' import view_measure, view_control, view_score_title, view_composer_name with context %}


{% block content %}
    <div class="container-md">
        <div class="card">
            <div class="the-end">Congratulations!</div>
        </div>
    </div>
    <div class="container-md">
        <div class="card">
            <div class="p content">You've completed the score:</div>
            <div class="p font-heading">
                {{  view_score_title(score.name, score.path) }}
            </div>
            <div class="p byline">
                {{ view_composer_name(score.composer) }}
            </div>
            <div class="p content">Next, you might want to:</div>
                <div class="ending-actions">
                    {% if score.composer == current_user %}
                        <div class="content">Edit the score so it's even better next time:</div>
                        <div class="page-controls">
                            {{ view_control(url_for('scores.update_score', score_path=score.path), "fa-pencil-alt") }}
                        </div>
                        <div class="content">Play it all over again.</div>
                        <div class="page-controls">
                            {{ view_control(url_for('scores.measure', score_path=score.path, measure_path=score.measures.0.path, autoplay='true'), "fa-play") }}
                        </div>
                    {% else %}
                        <div class="content">Star the score so you can find it later.</div>
                        <div class="page-controls">
                            {{ view_control(url_for('users.favorites'), "fa-star") }}
                        </div>
                        <div class="content">Create your own variation of the score.</div>
                        <div class="page-controls">
                            {{ view_control(url_for('scores.copy_score', score_path=score.path), "fa-copy") }}
                        </div>
                    {% endif %}
                        <div class="content">Have a drink of water.</div>
                        <div class="page-controls">
                            {{ view_control(url_for('main.not_implemented'), "fa-glass-whiskey") }}
                        </div>
                        <div class="content">Go pee.</div>
                        <div class="page-controls">
                            {{ view_control(url_for('main.not_implemented'), "fa-toilet") }}
                        </div>
                </div>
        </div>
    </div>
{% endblock content %}

ka/templates/invite.html
{% extends "base.html" %}

{% from 'macros.html' import view_submit_button %}

{% block content %}
{% if success %}
    <div class="container-md">
        <div class="card">
            <div class="form-group">
                <div class="text-center content">
                    Invitation sent! Thank you.
                </div>
            </div>
        </div>
    </div>
{% elif current_user.invites_left < 1 %}
    <div class="container-md">
        <div class="card">
            <div class="form-group">
                <div class="text-center content">
                        Sorry, you don't have any invites left. Please request more by <a href="mailto:info@kamagape.com?subject=Requesting additional invites">emailing us</a>.
                </div>
            </div>
        </div>
    </div>
{% else %}
    <div class="container-md">
        <div class="card">
            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <legend class="font-sub-heading text-center"><span>We'll email an invite to this person.</span></legend>
                    <div class="form-group">
                        {{ form.email.label(class="form-control-label") }}
                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid", autofocus=True) }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class="form-control form-control-lg", autofocus=True) }}
                        {% endif %}
                    </div>
                </fieldset>
                <div class="form-group float-right">
                    <div class="page-controls">
                            {{ view_submit_button('fa-save') }}
                    </div>
                </div>

            </form>
        </div>
    </div>
    <div class="container-md">
        <div class="card ">
                <div class="text-center content">
                        You have {{ current_user.invites_left }} invites left.
                </div>
        </div>
    </div>
    {% if current_user.is_admin %}
        <div class="container-md">
            <div class="card ">
                <div class="text-center content">
                        <a href="{{ url_for('users.create_open_invite') }}">Create Invite Link</a>
                </div>
            </div>
        </div>
    {% endif %}
{% endif %}
{% endblock content %}

ka/templates/measure.html
{% extends "base.html" %}

{% from 'macros.html' import view_measure, view_button, view_score_title, view_composer_name, view_for_players with context %}

{% block content %}
    {{ view_measure(measure, prev_measure, next_measure, show_controls) }}

    <div class="container-md">
        <div class="card ">
            <div>from</div>
            <div class="p font-sub-heading">
                {{  view_score_title(score.name, score.path) }}
            </div>
            <div class="byline">
                {{ view_composer_name(score.composer) }}{{ view_for_players(score.for_players) }}
            </div>
        </div>
    </div>
{% endblock content %}

ka/templates/posts.html
{% extends "base.html" %}

{% from 'macros.html' import view_post_row, view_control, view_empty_control, view_composer_name with context %}

{% block content %}

    {% if filtered_on %}
    <div class="container-md">
        <div class="card">
            {% if filtered_on is User %}
                <div class="p font-sub-heading serif">Posts{{ view_composer_name(filtered_on) }}</div>
            {% endif %}
        </div>
    </div>
    {% endif %}

    {% for post in result.items %}
        {{ view_post_row(post) }}
    {% endfor %}

    {% if result.has_prev or result.has_next  %}
        <div class="container-md">
        <div class="card">
            <div class="page-controls">
                    {% if result.has_prev %}
                        {{ view_control(url_for('posts.posts', page=result.current_page - 1), "fa-step-backward") }}
                    {% else %}
                        {{ view_empty_control() }}
                    {% endif %}
                    {% if result.has_next %}
                            {{ view_control(url_for('posts.posts', page=result.current_page + 1), "fa-step-forward") }}
                    {% else %}
                        {{ view_empty_control() }}
                    {% endif %}
            </div>
        </div>
        </div>
    {% endif %}
{% endblock content %}

ka/templates/score.html
{% extends "base.html" %}

{% from 'macros.html' import view_score_header_with_controls, view_measure with context %}

{% block content %}
    {{ view_score_header_with_controls(score) }}
    {% for measure in measures %}
        {{ view_measure(measure) }}
    {% endfor %}
{% endblock content %}

ka/templates/theme.html
{% extends "base.html" %}

{% from 'macros.html' import view_post_row, view_score_header_row, view_control, view_empty_control, view_composer_name, view_user_summary, view_theme_name with context %}

{% block content %}

    <div class="container-md">
        <div class="card">
                <div class="font-sub-heading text-center">{{ view_theme_name(name) }} themed</div>
        </div>
    </div>

    {% for item in result.items %}
        {% if item is Score %}
        {{ view_score_header_row(item) }}
        {% elif item is Post %}
        {{ view_post_row(item) }}
        {% endif %}
    {% endfor %}

    {% if result.has_prev or result.has_next  %}
        <div class="container-md">
        <div class="card">
            <div class="page-controls">
                    {% if result.has_prev %}
                        {{ view_control(url_for('theme.theme', name=name, page=result.current_page - 1), "fa-step-backward") }}
                    {% else %}
                        {{ view_empty_control() }}
                    {% endif %}
                    {% if result.has_next %}
                            {{ view_control(url_for('theme.theme', name=name, page=result.current_page + 1), "fa-step-forward") }}
                    {% else %}
                        {{ view_empty_control() }}
                    {% endif %}
            </div>
        </div>
        </div>
    {% endif %}
{% endblock content %}

ka/templates/user_posts.html
{% extends "base.html" %}

{% from 'macros.html' import view_post_row, view_control, view_empty_control, view_composer_name with context %}

{% block content %}

    <div class="container-md">
        <div class="card">
                <div class="font-context">Posts{{ view_composer_name(filtered_on) }}</div>
        </div>
    </div>

    {% for post in result.items %}
        {{ view_post_row(post) }}
    {% endfor %}

    {% if result.has_prev or result.has_next  %}
        <div class="container-md">
        <div class="card">
            <div class="page-controls">
                    {% if result.has_prev %}
                        {{ view_control(url_for('posts.user_posts', user_path=filtered_on.path, page=result.current_page - 1), "fa-step-backward") }}
                    {% else %}
                        {{ view_empty_control() }}
                    {% endif %}
                    {% if result.has_next %}
                            {{ view_control(url_for('posts.user_posts', user_path=filtered_on.path, page=result.current_page + 1), "fa-step-forward") }}
                    {% else %}
                        {{ view_empty_control() }}
                    {% endif %}
            </div>
        </div>
        </div>
    {% endif %}
{% endblock content %}