ka/main/routes.py
from flask import Blueprint, request, render_template, abort
from flask_login import login_required
from sqlalchemy.orm import with_polymorphic
from ka.models import KaBase, User, Score, Post, Feature
from ka.database import get_page, PageResult
from ka import db
import random

main_app = Blueprint('main', __name__)


@main_app.route("/")
def index():
    return render_template('index.html', title='')


@main_app.route("/how-it-works")
def how_it_works():
    return render_template('how_it_works.html', title='')


@main_app.route("/privacy")
def privacy():
    return render_template('legal/privacy.html', title='')


@main_app.route("/terms_of_service")
def terms():
    return render_template('legal/terms.html', title='')


@main_app.route('/featured', methods=['GET'])
@login_required
def featured():
    page = request.args.get('page', 1, type=int)
    content = with_polymorphic(KaBase, [User, Score, Post], flat=True)
    page_result = get_page(
        db.session.query(content)
            .join(Feature, (Feature.content_id == content.id))
            .order_by(Feature.pinned.desc(), Feature.created.desc()),
        page
    )
    return render_template(
        'featured.html',
        result=page_result
    )


@main_app.route('/not_implemented', methods=['GET'])
@login_required
def not_implemented():
    return render_template('not_implemented.html')


# *************************************************
#  Landing
# *************************************************


@main_app.route('/landing', methods=['GET'])
def landing():
    return render_template('onboarding/landing.html')

@main_app.route('/communication', methods=['GET'])
def communication():
    return render_template('onboarding/communication.html')

@main_app.route('/spice', methods=['GET'])
def spice():
    return render_template('onboarding/spice.html')

@main_app.route('/tenminutes', methods=['GET'])
def tenminutes():
    return render_template('onboarding/tenminutes.html')


@main_app.route("/sample/<string:score_path>")
def sample(score_path):
    s = Score.query.filter_by(path=score_path).first()
    if not s:
        abort(404)
    variation = None
    if s.variation_on_id:
        variation = Score.query.get(s.variation_on_id)
    title = s.name + ' by ' + s.composer.name
    return render_template('score.html', title=title, score=s, variation=variation, measures=s.measures)



# *************************************************
#  Template Tests
# *************************************************


@main_app.app_template_test("User")
def is_user(obj):
    return isinstance(obj, User)

@main_app.app_template_test("Score")
def is_score(obj):
    return isinstance(obj, Score)

@main_app.app_template_test("Post")
def is_post(obj):
    return isinstance(obj, Post)

ka/templates/onboarding/communication.html
{% extends "base.html" %}

{% block content %}

<div class="container-md ">
    <div class="home-middle">
      <div class="">
          <p class="text-center">
              <span class="content white">
                  That's great. Let's get started!
              </span>
          </p>
      </div>
    </div>
    <div class="card orange-card">
        <p class="">
            <span class="accent-4 home-card-title"> Better Communication</span>
        </p>
        <p class="content">
           It's really hard to talk about sex. Whether you're afraid of being embarrassed, or offending you're partner, you are not alone. We get it. But it doesn't have to be that way.
        </p>
        <p class="content accent-4">
            Making sex fun to talk about, and giving partners an equal voice.
        </p>
    </div>
    <div class="card">
        <p class="content">
            Would you like to try . . .
        </p>
        <p>
            <a class="btn ob-btn ob-blue" href="{{ url_for('main.sample', score_path='Verbally-Getting-it-On__by__m') }}">Verbally Getting It On</a>
        </p>
        <p>
            <a class="btn ob-btn ob-green" href="{{ url_for('main.sample', score_path='Overcoming-embarrassment----Asking-for-what-you-want-and-like.__by__m') }}">Overcoming Embarrassment</a>
        </p>
        <p>
            <a class="btn ob-btn ob-purple" href="{{ url_for('main.sample', score_path='36-Questions__by__i') }}">36 Questions</a>
        </p>
    </div>

</div>


{% endblock %}

ka/templates/onboarding/landing.html
{% extends "base.html" %}

{% block content %}

<div class="container-md ">
    <div class="home-middle">
      <div class="">
          <p class="text-center">
              <span class="home-title">
                  Elevate Your Love Life
              </span>
          </p>
          </p>
      </div>
    </div>
    <div class="card">
        <p class="content">
            Are you interested in . . .
        </p>
        <ul>
            <li class="ob-li">
                <a class="btn ob-btn ob-blue" href="{{ url_for('main.communication') }}">Better communication?</a>
            </li>
            <li class="ob-li">
                <a class="btn ob-btn ob-green" href="{{ url_for('main.spice') }}">A dose of spice?</a>
            </li>
            <li class="ob-li">
                <a class="btn ob-btn ob-purple" href="{{ url_for('main.tenminutes') }}">Getting jiggy in 10 minutes?</a>
            </li>
        </ul>
    </div>

</div>


{% endblock %}

ka/templates/onboarding/spice.html
{% extends "base.html" %}

{% block content %}

<div class="container-md ">
    <div class="home-middle">
      <div class="">
          <p class="text-center">
              <span class="content white">
                  We got ya covered.
              </span>
          </p>
      </div>
    </div>
        <div class="card green-card">
            <p class="">
                <span class="accent-2 home-card-title">A Dose of Spice</span>
            </p>
            <p class="content">
                There's no manual for your body, or for your partner's. But learning what feels good doesn't have to be a trial-and-error process. People have been writing about sex for thousands of years: there's no shortage of ideas and techniques.
            </p>
            <p class="content accent-2">
                A single source for the best ideas for couples.
            </p>
        </div>
    <div class="card">
        <p class="content">
            What are you in the mood for?
        </p>
        <ul>
            <li class="ob-li">
                <a class="btn ob-btn ob-blue" href="{{ url_for('main.sample', score_path='Variation-on-Chocolate-for-Two__by__m') }}">Something Sweet</a>
            </li>
            <li class="ob-li">
                <a class="btn ob-btn accent-4" href="{{ url_for('main.sample', score_path='Game-Night__by__i') }}">Something Fun</a>
            </li>
            <li class="ob-li">
                <a class="btn ob-btn ob-purple" href="{{ url_for('main.sample', score_path='Kissing-with-Passion__by__m') }}">Something Intense</a>
            </li>
        </ul>
    </div>

</div>


{% endblock %}

ka/templates/onboarding/tenminutes.html
{% extends "base.html" %}

{% block content %}

<div class="container-md ">
    <div class="home-middle">
      <div class="">
          <p class="text-center">
              <span class="content white">
                  Right. Let's get to it!
              </span>
          </p>
      </div>
    </div>
        <div class="card purple-card">
            <p class="">
                <span class="accent-3 home-card-title">Practice</span>
            </p>
            <p class="content">
                How do you improve your physical relationship? The same way you get better at throwing a ball, or playing the piano. Practice. Just putting the time in, and getting a little better each attempt.
            </p>
            <p class="content accent-3">
                Now, there's something to put on your calendar, and something to reflect on.
            </p>
        </div>
    <div class="card">
        <p class="content">
            Which would you like to do in 10 minutes?
        </p>
        <ul>
            <li class="ob-li">
                <a class="btn ob-btn ob-blue" href="{{ url_for('main.sample', score_path='5-Minute-Foot-Massage__by__i') }}">Increase Passion</a>
            </li>
            <li class="ob-li">
                <a class="btn ob-btn ob-green" href="{{ url_for('main.sample', score_path='Massage-for-Relaxation__by__m') }}">Build Anticipation</a>
            </li>
            <li class="ob-li">
                <a class="btn ob-btn accent-4" href="{{ url_for('main.sample', score_path="Exploring-Wonderland----Wonderland's-Choice__by__m") }}">Live Your Fantasy</a>
            </li>
        </ul>
    </div>

</div>


{% endblock %}